### ISSUE TITLE
Adding a new coordinator to a campaign

### ISSUE THREAD

**Issue by MichaelNMaggs** [hatnote/montage#104]
A user coordinator should be able to add another user as a further coordinator.

This was previously  #37, now closed.  But attempting this on 21 Oct 2017 generates a permission error.

**Comment by yarl** [comment]
Hm, @slaporte: do you know anything regarding this one?

**Comment by slaporte** [comment]
Adding/removing coordinators is currently restricted to organizers/admins. I will give this back to coordinators. (Be careful not to remove yourself!)
