### ISSUE TITLE
Emergency: ranking round shows not enough pictures

### ISSUE THREAD

**Issue by fantasticfears** [hatnote/montage#111]
What I’ve done:

1. click in an ongoing ranking round. https://tools.wmflabs.org/montage/#/vote/201-round-3
2. Ranking photos and hit save.
3. system shows 100 of 106 appears. So the save fails. And I can’t see the page any more. But in the ranking round,
I did only see 100 photos instead of 106.

**Comment by leilaz** [comment]
@fantasticfears did you check your email? we responded to this question over email.

**Comment by fantasticfears** [comment]
Sorry, I've even checked my spam folder on gmail but I didn't found your email :(

**Comment by leilaz** [comment]
</facepalm> I hadn't noticed you were not in those threads. Just shared with you the response. I'm going to resolve this issue. Let's follow up in the email and if needed reopen this.

**Comment by yarl** [comment]
It's closed but it still should be handled on the front-end and backend (prevent 100+ ranking rounds).
