### ISSUE TITLE
Provide statistics feedback to voters

### ISSUE THREAD

**Issue by dschwen** [hatnote/montage#115]
Some contests suggest a curve grading for images (in particular in 5star mode, but maybe also in yes/no mode). It would be nice to see a bar graph (or even just percentage numbers) for the amount of the different ratings given by the current user.

**Comment by slaporte** [comment]
I like this idea. 

Are you interested in seeing your own rating stats, as a juror, or seeing the full jury's stats, as the campaign coordinator? Both?

**Comment by dschwen** [comment]
I think it would be unproblematic to show the juror's own voting stats. Jurywide stats could be an optional per round setting.

**Comment by MichaelNMaggs** [comment]
This would be very useful, as in WLM we often want to tell reviewers that they should select roughly, say, one in five images for the next round.
