### ISSUE TITLE
Hide details of old campaigns from jurors

### ISSUE THREAD

**Issue by MichaelNMaggs** [hatnote/montage#122]
When logging in, jurors that have used the tool previously are presented with a list of all old (completed) campaigns before the one that's currently live. I for example am shown 18 old entries, which means I have to scroll down 9 screens to get to the one that's live, right at the bottom.    Many of those I know nothing about (eg specific country-based campaigns for WLAfrica), even though I'm listed as having completed 100% against each one.

Would prefer to have all the old stuff hidden, or at least have the current campaign presented first.

**Comment by slaporte** [comment]
We just deployed a new version with an archive button to hide old campaigns. Thanks to @baturin and @mahmoud for this feature!

We auto-archived all the campaigns that closed in 2019. Coordinators can archive any other campaigns that are done, and can un-archive their campaigns if needed.
