### ISSUE TITLE
Error code 500 after login

### ISSUE THREAD

**Issue by papuass** [hatnote/montage#125]
<ExceptionInfo [AttributeError: 'JSONCookie' object has no attribute 'set_expires'] (27 frames, last=Callpoint('complete_login', 162, 'montage.public_endpoints', './montage/public_endpoints.py', 121, ' cookie.set_expires()'))>

**Comment by yarl** [comment]
Just to make sure, which environment is that (URL)?

**Comment by papuass** [comment]
It was on https://tools.wmflabs.org/montage/ but now seems to be resolved.
