### ISSUE TITLE
Unable to run Montage in Firefox

### ISSUE THREAD

**Issue by MichaelNMaggs** [hatnote/montage#136]
On clicking the link 'Log in using Wikimedia account', Firefox throws the error message:

**Internal server error**

_<ExceptionInfo [AttributeError: 'JSONCookie' object has no attribute 'set_expires'] (27 frames, last=Callpoint('complete_login', 162, 'montage.public_endpoints', './montage/public_endpoints.py', 121, ' cookie.set_expires()'))>

Error type: http://docs.python.org/2/library/exceptions.html#exceptions.AttributeError_

Same result on several machines.  Firefox 62.0.3 for Mac.

**Comment by slaporte** [comment]
Does it work now?

I've upgraded to clastic 0.50, which includes a stale cookie fix that may be related to your issue. Let me know if it's still problem.

**Comment by MichaelNMaggs** [comment]
No longer see that error, but instead when I click on 'Log in using Wikimedia account', Firefox simply reloads the same 'Please log in' page.

**Comment by PierreSelim** [comment]
Works fine here on:
* Firefox 63.0b12 win64
* Firefox 62.0 linux64 (ubuntu 18.04.1 LTS)

**Comment by MichaelNMaggs** [comment]
Mac results:

- Now working:  Firefox 62.0.3 Sierra 10.12.6
- Reloads login page:  Firefox 62.0.3 Mojave 10.14

**Comment by MichaelNMaggs** [comment]
A year later, and Firefox 69.0 on Mac is working fine.

**Comment by lgelauff** [comment]
Seems fixed, closing.
