### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by susannaanas** [hatnote/montage#179]
![image](https://user-images.githubusercontent.com/4725416/98777411-55e79000-23f9-11eb-893d-9d949abb2e55.png)

**Comment by slaporte** [comment]
Montage is not working at the moment due to Toolforge database maintenance. We'll hopefully have an update shortly.

See: https://phabricator.wikimedia.org/T266587

**Comment by susannaanas** [comment]
Thank you, I also found information about this.
