### ISSUE TITLE
Round url shows empty screen if not logged in

### ISSUE THREAD

**Issue by themudo** [hatnote/montage#240]
### What happens now?
If we invite jury to vote on a round with the specific link to that round (for example, https://montage.toolforge.org/#!/vote/3533-primeira-ronda), and the juror is not logged in, he sees a blank screen or something trying to load and never does (see screenshot below).
![imagem](https://github.com/user-attachments/assets/ee7c5cec-bc8c-404a-bc07-d8d770e207da)

### What would be expected?
Juror should see warning that they are not logged in and a button to log in or a link to montage main page.

**Comment by mahmoud** [comment]
Great point. This should be addressed in the new version of the montage UI, cc @Jayprakash-SE

**Comment by Jayprakash-SE** [comment]
In the new version of Montage. There is an auth guard that will redirect users to the login page if they try to access pages those require login.
