### ISSUE TITLE
Adding new entries during a capaign

### ISSUE THREAD

**Issue by slaporte** [hatnote/montage#35]
A coordinator may want to start voting in the first round of a campaign, with an option to load in more photos as they are submitted. This feature could be limited to the first round and a non-ranking round for the sake of fairness. 

Starting voting early is particularly helpful for campaigns with a large number of entries.

**Comment by leilaz** [comment]
@slaporte is this a repeat of https://github.com/hatnote/montage/issues/46 ?

**Comment by slaporte** [comment]
Yes, I'm closing this as a duplicate.
