### ISSUE TITLE
Adding new jurors and increasing Quorum

### ISSUE THREAD

**Issue by papuass** [hatnote/montage#42]
Our WLE 2017 Latvia judging round is in progress but we wanted to add more jurors to it.

When I add new juror, remaining tasks are distributed between new and existing jurors. There is no way to change Quorum value.

We want to go from 3 to 5 jurors where every jurors has to evaluate all images.

**Comment by mahmoud** [comment]
Hi @papuass! We support this in the next version of Montage (scheduled to be released for WLM 2017). I'll talk to @slaporte about a potential backporte.

**Comment by mahmoud** [comment]
@papuass it seems feasible to backport this to `montage-beta`, when would you need this by? If we can get it live within 2-3 days is that fast enough?

**Comment by papuass** [comment]
2-3 days would be good enough. As long as it does not take a huge effort we would like to use this feature.

**Comment by mahmoud** [comment]
Hi @papuass, we actually have a fix for this in montage-beta now, but I noticed that your round (assuming round 202) only has 3 active jurors (and one inactive). You'll need to add more jurors before we can increase the quorum. :)

**Comment by papuass** [comment]
There has been a delay on our side. I added fourth judge, but we are still waiting for the fifth.

**Comment by mahmoud** [comment]
No worries, @papuass. Simply let me know when the jury is ready and I will update accordingly. Thanks for the update!

**Comment by papuass** [comment]
I have added the fifth juror. Please create tasks for two new jurors.

**Comment by mahmoud** [comment]
Alrighty, 216 more tasks distributed, let me know if there are any more issues! :)

**Comment by papuass** [comment]
Thanks, seems to be working fine.
