### ISSUE TITLE
https://tools.wmflabs.org/montage-beta should redirect

### ISSUE THREAD

**Issue by Jarry1250** [hatnote/montage#5]
I keep forgetting to add the /#/ :) (Sorry, not sure if you have a separate issues tracker for specifically that installation or not.)

**Comment by mahmoud** [comment]
Agreed! Even I run into this issue, and I'm not sure why the trailing slash is necessary. @yarl, have you seen this behavior? Is there anything I need to change on the backend to make this work, or is it just an frontend thing?

**Comment by yarl** [comment]
Hitting https://tools.wmflabs.org/montage-dev will result 
`GET https://tools.wmflabs.org/dist/bundle.min.js?v=16.10.15 404 ()`

In HTML file we have:
`<script type="text/javascript" src="dist/bundle.min.js?v=16.10.15"></script>`

Is there any other solution than absolute path?

**Comment by yarl** [comment]
@mahmoud can we modify `.htaccess` file, so it will add trailing slash? That's probably the easiest solution.

**Comment by mahmoud** [comment]
That's a good question. I haven't done it yet, and I'm not sure how to do it for Python WSGI stuff (we have a `www` directory but not a `public_html`). Let me ask @yuvipanda.

**Comment by slaporte** [comment]
Fixed on both montage-dev and montage-beta.
