### ISSUE TITLE
Voting buttons vs shortcuts

### ISSUE THREAD

**Issue by sabas** [hatnote/montage#52]
A comment from the an italian juror on the voting interface:
* The accept/decline buttons change position based on the title length. It should be better if the title would resize while the buttons are in a fixed position.
* The keyboard shortcuts alternative should be made more evident.
* Perhaps the description could be made smaller wrt the voting area

**Comment by yarl** [comment]
@sabas can you clarify last two points?

**Comment by sabas** [comment]
Hi @yarl I ask the user to clarify.

**Comment by sabas** [comment]
Here it is
![montage_ui](https://user-images.githubusercontent.com/1304918/31178248-c0f82cf6-a918-11e7-8a9e-c311ee85e632.png)
