### ISSUE TITLE
Show distinction between campaign and rounds

### ISSUE THREAD

**Issue by MichaelNMaggs** [hatnote/montage#55]
On the Add Rounds page, the Edit Campaign link looks as though it allows editing of the entire page, and it's not immediately clear that there is a definite difference between editing those things that are part of a campaign and those that are part of the round being set up.

Suggest that the editable campaign features be delimited from the rest of the page in some way, eg by being set off in a different colour

**Comment by lgelauff** [comment]
I believe this has been resolved in the mean time. Please reopen if I'm mistaken.
