### ISSUE TITLE
Deleting rounds

### ISSUE THREAD

**Issue by MichaelNMaggs** [hatnote/montage#66]
Could a Delete Round button be provided for all organisers, by default? At present, deleting a round requires developer assistance

**Comment by leilaz** [comment]
@yarl can you confirm if Delete Round works for the coordinators?

**Comment by slaporte** [comment]
The backend path is [/v1/admin/round/<round_id:int>/cancel](https://github.com/hatnote/montage/blob/master/montage/docs/api.md#v1adminroundround_idintcancel) to delete a round.

**Comment by yarl** [comment]
Yes, it's done in 9efa7995e6186d6b897341bfd05dc07f6200f920. You need to click Edit Round, and you will find Delete Round on the bottom. Please reopen if not working.
