### ISSUE TITLE
Easier access to the Edit Previous Votes page

### ISSUE THREAD

**Issue by MichaelNMaggs** [hatnote/montage#69]
The overview/Edit Previous Votes page seems to be accessible to jurors only when they have just logged in. There's no link from the voting page (at least for yes/no which is all I have tried so far). Hitting Back on the browser may work, but that's not an obvious thing to have to do.

Could a direct link be added on the voting page?

**Comment by leilaz** [comment]
Yes, this option can become much more discoverable. :)

@yarl et al.: there are a few things we want the juror to be able to go back to if needed. Maybe now is a good time to think about where to put them. For example, we can have a set of tabs on top of the voting page that include options such as: Instructions (for taking the juror to a page where they can read the complete instructions of the round), Edit Votes, ...
