### ISSUE TITLE
'Voting details' section on coordinator page is unclear

### ISSUE THREAD

**Issue by MichaelNMaggs** [hatnote/montage#73]
The Voting details section on the coordinators' page isn't at all clear. We are part way though our round 1 - a yes/no round - and this is what it says:

0.00/10 5770 
3.33/10 4 
5.00/10 658 
10.00/10 1238 

None of that obviously relates to yes/no voting results.

**Comment by yarl** [comment]
It relates in a way. Think of Yes as 10/10 and No as 0/10.
In your example 658 photos got the same amount of Yeses and Nos. 1238 photos got only Yeses, etc.

I know current representation is bad, I'm open for changes.

**Comment by MichaelNMaggs** [comment]
OK, thanks. That's very useful information, but perhaps a slightly different presentation would help. Suggest something like this (the table is supposed to be in proper justified columns but it doesn't display like that):

## This round voting summary to date

_Score        No of images_
0%                5770
33%                    4
50%               658
100%            1238

The score for each image is calculated as **[yes votes so far] / [total votes so far]**, expressed as a percentage.

**Comment by yarl** [comment]
Yes, I was thinking about percentage, but I would like also keep diagram for better visualisation.

**Comment by MichaelNMaggs** [comment]
Agreed. Diagram is very useful.

**Comment by slaporte** [comment]
If you want to convert these to stars, it's: score/10 * 4 + 1. That means that 0.000 is an average of 1 star, 3.33 is an average of 2.33 stars, 10 is an average of 5 stars. The odd decimals are due to the range of responses from your jury.

If you want to convert these to yes/no, 0.0 is no and 10.0 is yes.

You could say:

# Voting summary to date
5 stars: 1238
3 stars 658
2.33 stars: 4
1 star: 5770

It would be most intuitive for me as a [stacked bar](https://s3-eu-central-1.amazonaws.com/centaur-wp/creativereview/prod/content/uploads/2016/01/02_CR__Pay_Attention-1.jpg), instead of a pie, with number of files on right and average stars on the left.

**Comment by MichaelNMaggs** [comment]
Average stars makes sense for starred rounds, but would be very confusing for yes/no rounds. Much prefer those to list % of yes votes.

Not sure about pie chart vs stacked bars, as I haven't yet seen how round advancement works.

**Comment by MichaelNMaggs** [comment]
While you're looking at this, it would be good to have a quick indicator of overall voting progress on the coordinator page. You already have figures for Open Tasks and Tasks, and diving one by the other would give an overview of how the current round is progressing. Could display as a percentage, preferably with a progress bar.

In the table, I'd re-order

Open tasks 
Files 
Tasks 
Uploaders

to read

Uploaders
Files 
Tasks 
Open tasks

**Comment by MichaelNMaggs** [comment]
Just to note that #50 is about showing progress to an individual juror. This one is about showing overall round progress to the coordinator

**Comment by atsirlin** [comment]
Right now we have the diagram and the voting statistics. Is there anything else to be done here? 
I would not re-order the entries in the table. For me they are OK, and I guess there is no strong rationale, just a matter of taste

**Comment by lgelauff** [comment]
seems resolved. Please reopen if I'm wrong.
