### ISSUE TITLE
Fixing link for editing votes

### ISSUE THREAD

**Issue by leilaz** [hatnote/montage#75]
Once a juror finishes their voting, they see the following screen:
![screenshot from 2017-10-05 18-11-00](https://user-images.githubusercontent.com/682170/31259038-91bcedce-a9f8-11e7-8bd6-ce7c8b9ec878.png)
The hyperlink on "this page" doesn't work. Please fix this. :)

**Comment by leilaz** [comment]
@yarl is the change pushed to montage? When I hover over "this page" I see "https://tools.wmflabs.org/montage/" and when I click on it, nothing happens.

**Comment by yarl** [comment]
It's deployed now.

**Comment by MichaelNMaggs** [comment]
Not working.  Get rotating timer ...

**Comment by yarl** [comment]
Fixed, see #90.
