### ISSUE TITLE
Help!  Cannot start round 2

### ISSUE THREAD

**Issue by MichaelNMaggs** [hatnote/montage#89]
Can someone help urgently please with a problem with the UK campaign?

I've told our jurors that I will send out round 2 instructions **today**, Wed 11th Oct, but I'm unable to start the next round as the Finalize button for round 1 is permanently greyed out.

Perhaps the reason is that two of our 21 jurors have not completed round 1 by the deadline, but I can't wait any longer for them.  I've downloaded the results so far, have completed all the missing reviews offline and have a spreadsheet with list of images all ready for round 2.  I need to be able to close the existing round so that I can upload the list and get going with round 2.

**Comment by slaporte** [comment]
Here are two quick options for you:

 1. Make a list of the entries to advance to Round 2, and then use that list to start a new campaign in Montage. This means you won't get a full report of Round 1 at the end, unfortunately, but it will work fine.
 2. Assign a new juror to do these outstanding ratings, or ask the jurors to log back in and do a few more ratings.

We may want a feature to allow for emergency vote completion, but it would take a few days (at the very least) to design and build. One design principle for us has been that Montage should protect the integrity of the ratings by separating coordinators from the juror's decisions. Allowing coordinators to go in an adjust voting makes practical sense—you aren't the first WLM organizer to run into this issue with one or two outstanding votes and a looming deadline for the next round. There are a few alternative approaches, each with some pros/cons.

**Comment by MichaelNMaggs** [comment]
Thanks. Easiest for me would be to quickly start a new campaign, but I get the error message

Access forbidden: must have maintainer permissions

**Comment by slaporte** [comment]
Here's your campaign: https://tools.wmflabs.org/montage/#/campaign/56-wiki-loves-monuments-2017-gb-part-ii

You can import the files into your first round as a list of filenames, without "File:", one per line. I'd recommend saving them as a [gist](https://gist.github.com/) (it can be secret), and then pasting the raw file URL into Montage.

**Comment by MichaelNMaggs** [comment]
Wonderful. Thank you!

Michael

**Comment by MichaelNMaggs** [comment]
@slaporte  Have added jurors, made and pasted the gist, and created the round.  It took a long time uploading, and then returned to the create round page.  The round seems to be there, but can't be used as it claims to have no uploaded images.  

Are you able to upload from your end?  The gist is
https://gist.github.com/MichaelNMaggs/29dbee7305dbeaacaf56d3fa332487bc

**Comment by mahmoud** [comment]
Hey Michael! Sorry you're having trouble. I've looked into this and it appears to be a timeout on the database. Possibly it's running slow from load, but I'll continue searching for a technical solution that'll make this more robust. Thanks for your patience!

**Comment by slaporte** [comment]
I added the files to your round, and it's ready to start voting. I'll follow up via email on three quirks I noticed with your file list.

**Comment by MichaelNMaggs** [comment]
OK now, thanks
