### ISSUE TITLE
Line breaks in Round Directions

### ISSUE THREAD

**Issue by nikikana** [hatnote/montage#9]
Thanks for this great tool! I've got a feature request: 

**Make line breaks visible in Round Directions** 
This would be really helpful for readability when writing out judging criteria for a ranked round. Currently line breaks don't appear; just a big block of text, which can be hard to digest especially when comprehending directions that include a list of how to interpret 1-5 stars, etc.

**Comment by yarl** [comment]
It's fixed in ver. 16.10.20 and live now on beta.

**Comment by nikikana** [comment]
thanks!

2016-10-16 6:47 GMT-07:00 Paweł Marynowski <notifications@github.com>:
